//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Kiosk
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class livecasinoEntities : DbContext
    {
        public livecasinoEntities()
            : base("name=livecasinoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_CONFIG_VALUES> T_CONFIG_VALUES { get; set; }
        public virtual DbSet<T_GAME_TYPE_CONFIG_VALUES> T_GAME_TYPE_CONFIG_VALUES { get; set; }
        public virtual DbSet<TO_OPERATOR_CONFIG_VALUES> TO_OPERATOR_CONFIG_VALUES { get; set; }
        public virtual DbSet<T_GAME_TYPES_CONFIG> T_GAME_TYPES_CONFIG { get; set; }
    }
}
