//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Kiosk
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CONFIG_VALUES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_CONFIG_VALUES()
        {
            this.T_GAME_TYPE_CONFIG_VALUES = new HashSet<T_GAME_TYPE_CONFIG_VALUES>();
            this.T_GAME_TYPES_CONFIG = new HashSet<T_GAME_TYPES_CONFIG>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string DEFAULT_VALUE { get; set; }
        public int CONFIG_TYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GAME_TYPE_CONFIG_VALUES> T_GAME_TYPE_CONFIG_VALUES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GAME_TYPES_CONFIG> T_GAME_TYPES_CONFIG { get; set; }
    }
}
