//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Kiosk
{
    using System;
    using System.Collections.Generic;
    
    public partial class TO_OPERATOR_CONFIG_VALUES
    {
        public int OPERATOR_ID { get; set; }
        public int CONFIG_ID { get; set; }
        public string OPERATOR_VALUE { get; set; }
    }
}
